# Generated by Django 5.0 on 2023-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
