# Generated by Django 5.0 on 2023-12-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_payment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_on',
        ),
    ]
