# Generated by Django 5.0 on 2023-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_review_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled'), ('checked out', 'checked out')], default='active', max_length=255),
        ),
    ]
