# Generated by Django 5.0 on 2024-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='Kathmandu', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='hotel@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='9840000000', max_length=255),
        ),
    ]
